packages:
  - packages/*
  - apps/*

catalogs:
  eslint:
    '@eslint/js': ^9.39.1
    eslint: ^9.39.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    globals: ^16.5.0
  lucide:
    lucide-react: ^0.562.0
  radix-ui:
    '@radix-ui/colors': ^3.0.0
    '@radix-ui/react-toolbar': ^1.1.11
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/themes': ^3.2.1
    '@radix-ui/react-dropdown-menu': ^2.1.16
  react:
    '@types/react': ^19.2.5
    '@types/react-dom': ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0
  sass-embedded:
    sass-embedded: ^1.97.3
  tailwind:
    autoprefixer: ^10.4.20
    postcss: ^8.4.49
    tailwindcss: ^4.0.0
  tiptap:
    '@tiptap/core': 3.16.0
    '@tiptap/extension-highlight': 3.16.0
    '@tiptap/extension-horizontal-rule': 3.16.0
    '@tiptap/extension-image': 3.16.0
    '@tiptap/extension-list': 3.16.0
    '@tiptap/extension-subscript': 3.16.0
    '@tiptap/extension-superscript': 3.16.0
    '@tiptap/extension-text-align': 3.16.0
    '@tiptap/extension-typography': 3.16.0
    '@tiptap/extensions': 3.16.0
    '@tiptap/pm': 3.16.0
    '@tiptap/react': 3.16.0
    '@tiptap/starter-kit': 3.16.0
  typescript:
    '@types/node': ^24.10.1
    typescript: ~5.9.3
    typescript-eslint: ^8.46.4
  vite:
    '@vitejs/plugin-react': ^5.1.1
    vite: ^7.2.4
  react-hotkeys-hook:  
    react-hotkeys-hook: ^5.2.3
  dnd-kit:
    "@dnd-kit/core": "6.3.1"
    "@dnd-kit/modifiers": "9.0.0"
  react-resizable-panels:
    "react-resizable-panels": "^4.4.1"
