packages:
  - 'packages/*'
  - 'apps/*'

catalogs:
  # React related packages
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    '@types/react': ^19.2.5
    '@types/react-dom': ^19.2.3

  # Tiptap editor packages
  tiptap:
    '@tiptap/core': ^3.15.3
    '@tiptap/pm': ^3.15.3
    '@tiptap/react': ^3.15.3
    '@tiptap/starter-kit': ^3.15.3
    '@tiptap/simple-editor': ^0.1.5

  # Radix UI packages
  radix-ui:
    '@radix-ui/themes': ^3.2.1

  # Vite related packages
  vite:
    vite: ^7.2.4
    '@vitejs/plugin-react': ^5.1.1

  # TypeScript related packages
  typescript:
    typescript: ~5.9.3
    typescript-eslint: ^8.46.4
    '@types/node': ^24.10.1

  # ESLint related packages
  eslint:
    eslint: ^9.39.1
    '@eslint/js': ^9.39.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    globals: ^16.5.0

  # Tailwind CSS related packages
  tailwind:
    tailwindcss: ^4.0.0
    autoprefixer: ^10.4.20
    postcss: ^8.4.49
  # lucide packages
  lucide:
    lucide-react: ^0.562.0
